// User Profile
export type Gender = 'male' | 'female';
export type ActivityLevel = 'sedentary' | 'light' | 'moderate' | 'active';

export interface UserProfile {
  height: number;       // cm
  weight: number;        // kg
  age: number;
  gender: Gender;
  activityLevel: ActivityLevel;
  goalWeight: number;
  targetDays: number;
  bmr: number;
  tdee: number;
  dailyCalorieTarget: number;
  createdAt?: Date;
}

// Food
export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';
export type ExerciseType = 'cardio' | 'strength';

export interface FoodItem {
  id: string;
  name: string;
  estimatedCalories: number;
  calorieRange?: [number, number];
  portion: string;
}

export interface Meal {
  id: string;
  type: MealType;
  items: FoodItem[];
  totalCalories: number;
  photoUrl?: string;
  createdAt: Date;
}

// Exercise
export interface Exercise {
  id: string;
  name: string;
  type: ExerciseType;
  duration?: number;     // minutes for cardio
  sets?: number;         // for strength
  reps?: number;         // for strength
  caloriesBurned: number;
  description: string;
}

// Daily Plan
export interface CompletedStatus {
  breakfast: boolean;
  lunch: boolean;
  dinner: boolean;
  snack: boolean;
  exercises: boolean;
}

export interface DailyPlan {
  id: string;
  date: string;          // YYYY-MM-DD
  meals: Meal[];
  exercises: Exercise[];
  completed: CompletedStatus;
  totalCaloriesConsumed: number;
  totalCaloriesBurned: number;
  aiGenerated: boolean;  // whether exercise plan was generated by AI
}

// Weight Record
export interface WeightRecord {
  date: string;
  weight: number;
  note?: string;
  createdAt?: Date;
}

// Notification Settings
export interface NotificationSettings {
  breakfast: { enabled: boolean; time: string };
  lunch: { enabled: boolean; time: string };
  dinner: { enabled: boolean; time: string };
  exercise: { enabled: boolean; time: string };
  dailySummary: { enabled: boolean; time: string };
}

// Local user (replaces Firebase User)
export interface LocalUser {
  userId: string;
}
